import io
import requests
import numpy as np

# Get a video generated by LTX Video from Modemm

params = {"stream": False}
data = {"prompt": "meow", "padding": False}

# This returns a npy file as bytes with T5 prompt embeds for our prompt
prompt_embeds = requests.get("http://127.0.0.1:14145/modemm/request/T5", params=params, json=data).content

# Turn the bytes into a readable file-like object
prompt_embeds = io.BytesIO(prompt_embeds)

# Load the npy file into a numpy array
prompt_embeds = np.load(prompt_embeds)

# You can now manipulate the prompt embeds however you want
...

# Turn them back into a file object and then bytes to send back to Modemm
prompt_file = io.BytesIO()
np.save(prompt_file, prompt_embeds)
prompt_file.seek(0)
prompt_file = prompt_file.read()
